#!/usr/bin/env python3
"""
Two-plaquette 2D strip of charged mirror-Fock/SMG cells with Z3 open links.

This is the finite-volume escalation of css_2d_mirror_fock_plaquette_lanczos.py:

  * 2x1 plaquette strip: 6 sites, 7 open links, 2 magnetic plaquettes,
  * states/charge=2, the first local truncation containing a mirror excitation,
  * exact vertex Gauss-law basis generated by solving the Z3 incidence equations,
  * sparse/matrix-free Lanczos using stored transition arrays, not a dense matrix.

The goal is not a thermodynamic proof. After the hopping-truncation audit, this
should be read as a low-cutoff finite-volume check only: the same calculation
must be repeated at larger local cutoffs where hopping visibly moves the gap
before it can be used as evidence for mirror-gap stability.
"""

import importlib.util
from itertools import product
from pathlib import Path

import numpy as np


HERE = Path(__file__).resolve().parent
PLAQUETTE_PATH = HERE / "css_2d_mirror_fock_plaquette_lanczos.py"


def load_plaquette_module():
    spec = importlib.util.spec_from_file_location("plaquette", PLAQUETTE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


plaquette = load_plaquette_module()


def hd(title):
    print("\n" + "=" * 78)
    print(title)
    print("=" * 78)


def vertex_index(x, y, nx):
    return y * (nx + 1) + x


def rectangular_geometry(nx, ny):
    edges = []
    edge_index = {}
    for y in range(ny + 1):
        for x in range(nx):
            edge_index[("h", x, y)] = len(edges)
            edges.append((vertex_index(x, y, nx), vertex_index(x + 1, y, nx)))
    for y in range(ny):
        for x in range(nx + 1):
            edge_index[("v", x, y)] = len(edges)
            edges.append((vertex_index(x, y, nx), vertex_index(x, y + 1, nx)))

    plaquette_shifts = []
    for y in range(ny):
        for x in range(nx):
            shift = np.zeros(len(edges), dtype=int)
            shift[edge_index[("h", x, y)]] += 1
            shift[edge_index[("v", x + 1, y)]] += 1
            shift[edge_index[("h", x, y + 1)]] -= 1
            shift[edge_index[("v", x, y)]] -= 1
            plaquette_shifts.append(tuple(int(value % 3) for value in shift))
    return (nx + 1) * (ny + 1), edges, plaquette_shifts


def incidence_matrix(n_vertices, edges):
    matrix = np.zeros((n_vertices, len(edges)), dtype=int)
    for col, (tail, head) in enumerate(edges):
        matrix[tail, col] = 1
        matrix[head, col] = -1
    return matrix % 3


def inv3(value):
    value %= 3
    if value == 1:
        return 1
    if value == 2:
        return 2
    raise ZeroDivisionError("0 has no inverse in F3")


def solve_mod3_with_nullspace(matrix, rhs):
    aug = np.concatenate([matrix.copy() % 3, rhs[:, None] % 3], axis=1)
    n_rows, n_cols = matrix.shape
    pivots = []
    row = 0
    for col in range(n_cols):
        pivot = None
        for candidate in range(row, n_rows):
            if aug[candidate, col] % 3 != 0:
                pivot = candidate
                break
        if pivot is None:
            continue
        if pivot != row:
            aug[[row, pivot]] = aug[[pivot, row]]
        aug[row] = (aug[row] * inv3(aug[row, col])) % 3
        for other in range(n_rows):
            if other == row:
                continue
            factor = aug[other, col] % 3
            if factor:
                aug[other] = (aug[other] - factor * aug[row]) % 3
        pivots.append(col)
        row += 1
        if row == n_rows:
            break

    for check in range(row, n_rows):
        if np.all(aug[check, :n_cols] % 3 == 0) and aug[check, n_cols] % 3 != 0:
            return None, []

    free_cols = [col for col in range(n_cols) if col not in pivots]
    particular = np.zeros(n_cols, dtype=int)
    for pivot_row, pivot_col in enumerate(pivots):
        particular[pivot_col] = aug[pivot_row, n_cols] % 3

    nullspace = []
    for free_col in free_cols:
        vector = np.zeros(n_cols, dtype=int)
        vector[free_col] = 1
        for pivot_row, pivot_col in enumerate(pivots):
            vector[pivot_col] = (-aug[pivot_row, free_col]) % 3
        nullspace.append(vector)
    return particular, nullspace


def flux_solutions(charge_tuple, incidence):
    rhs = np.array([(-charge) % 3 for charge in charge_tuple], dtype=int)
    particular, nullspace = solve_mod3_with_nullspace(incidence, rhs)
    if particular is None:
        return []
    out = []
    for coeffs in product(range(3), repeat=len(nullspace)):
        flux = particular.copy()
        for coeff, vector in zip(coeffs, nullspace):
            flux = (flux + coeff * vector) % 3
        out.append(tuple(int(value) for value in flux))
    return out


def shift_fluxes(fluxes, shift, amount):
    return tuple((value + amount * delta) % 3 for value, delta in zip(fluxes, shift))


def shift_link(fluxes, link, amount):
    out = list(fluxes)
    out[link] = (out[link] + amount) % 3
    return tuple(out)


class StripHamiltonian:
    def __init__(self, beta, hopping, states_per_charge=2, nx=2, ny=1):
        self.beta = beta
        self.hopping = hopping
        self.g2 = 1 / beta
        self.n_vertices, self.edges, self.plaquette_shifts = rectangular_geometry(nx, ny)
        self.incidence = incidence_matrix(self.n_vertices, self.edges)
        self.energies, self.charges, self.annihilators, _ = (
            plaquette.block.local_mirror_dressed_block(states_per_charge)
        )
        self.ann, self.create = plaquette.transition_tables(self.annihilators)
        self.basis, self.index = self.build_basis()
        self.dim = len(self.basis)
        self.diagonal = np.zeros(self.dim)
        self.matter_diagonal = np.zeros(self.dim)
        for pos, (config, fluxes) in enumerate(self.basis):
            matter = sum(self.energies[state] for state in config)
            electric = self.g2 * sum(plaquette.electric_energy(flux) for flux in fluxes)
            self.matter_diagonal[pos] = matter
            self.diagonal[pos] = matter + electric
        self.rows, self.cols, self.data = self.build_transition_arrays()

    def build_basis(self):
        local_dim = len(self.charges)
        basis = []
        flux_cache = {}
        for config in product(range(local_dim), repeat=self.n_vertices):
            charge_tuple = tuple(int(self.charges[state]) for state in config)
            if sum(charge_tuple) % 3 != 0:
                continue
            if charge_tuple not in flux_cache:
                flux_cache[charge_tuple] = flux_solutions(charge_tuple, self.incidence)
            for fluxes in flux_cache[charge_tuple]:
                basis.append((tuple(config), fluxes))
        return basis, {item: pos for pos, item in enumerate(basis)}

    def add_transition(self, rows, cols, data, row, col, coeff):
        if abs(coeff) > 1e-14:
            rows.append(row)
            cols.append(col)
            data.append(coeff)

    def build_transition_arrays(self):
        rows = []
        cols = []
        data = []
        for col, (config, fluxes) in enumerate(self.basis):
            for shift in self.plaquette_shifts:
                for amount in [1, -1]:
                    target = (config, shift_fluxes(fluxes, shift, amount))
                    row = self.index.get(target)
                    if row is not None:
                        self.add_transition(rows, cols, data, row, col, -(self.beta / 2))

            if abs(self.hopping) < 1e-15:
                continue
            config_list = list(config)
            for link, (tail, head) in enumerate(self.edges):
                old_tail = config_list[tail]
                old_head = config_list[head]
                for mode in range(len(self.ann)):
                    for charge in range(3):
                        for new_tail, amp_tail in self.create[mode][charge][old_tail]:
                            for new_head, amp_head in self.ann[mode][charge][old_head]:
                                new_config = list(config_list)
                                new_config[tail] = new_tail
                                new_config[head] = new_head
                                target = (
                                    tuple(new_config),
                                    shift_link(fluxes, link, charge),
                                )
                                row = self.index.get(target)
                                if row is not None:
                                    self.add_transition(
                                        rows,
                                        cols,
                                        data,
                                        row,
                                        col,
                                        -self.hopping * amp_tail * amp_head,
                                    )
                        for new_tail, amp_tail in self.ann[mode][charge][old_tail]:
                            for new_head, amp_head in self.create[mode][charge][old_head]:
                                new_config = list(config_list)
                                new_config[tail] = new_tail
                                new_config[head] = new_head
                                target = (
                                    tuple(new_config),
                                    shift_link(fluxes, link, -charge),
                                )
                                row = self.index.get(target)
                                if row is not None:
                                    self.add_transition(
                                        rows,
                                        cols,
                                        data,
                                        row,
                                        col,
                                        -self.hopping * amp_tail * amp_head,
                                    )
        return (
            np.array(rows, dtype=np.int64),
            np.array(cols, dtype=np.int64),
            np.array(data, dtype=complex),
        )

    def matvec(self, vector):
        out = self.diagonal * vector
        np.add.at(out, self.rows, self.data * vector[self.cols])
        return out

    def matter_expectation(self, vector):
        return float(np.real(np.vdot(vector, self.matter_diagonal * vector)))


def strip_matter_gap(model, n_iter=70, n_eigs=18):
    evals, vectors = plaquette.lanczos_lowest(model, n_iter=n_iter, n_eigs=n_eigs)
    full_gap = float(evals[1] - evals[0])
    ground_matter = model.matter_expectation(vectors[:, 0])
    matter_gap = float("inf")
    for index in range(1, vectors.shape[1]):
        delta_matter = model.matter_expectation(vectors[:, index]) - ground_matter
        if delta_matter > 0.5:
            matter_gap = float(evals[index] - evals[0])
            break
    return full_gap, matter_gap


def hermiticity_probe(model, seed=917):
    rng = np.random.default_rng(seed)
    left = rng.normal(size=model.dim) + 1j * rng.normal(size=model.dim)
    right = rng.normal(size=model.dim) + 1j * rng.normal(size=model.dim)
    mismatch = np.vdot(left, model.matvec(right)) - np.vdot(model.matvec(left), right)
    scale = np.linalg.norm(left) * np.linalg.norm(right)
    return float(abs(mismatch) / scale)


def scan():
    hd("A. Two-Plaquette Strip Lanczos Scan")
    print("  states/charge=2, 6 sites, 7 links, 2 plaquettes")
    print("  beta   t      dim      nnz offdiag   full gap  matter gap  herm")
    results = []
    for beta in [0.5, 1.0]:
        for hopping in [0.1, 0.2]:
            model = StripHamiltonian(beta=beta, hopping=hopping)
            herm = hermiticity_probe(model)
            assert herm < 1e-10
            full_gap, matter_gap = strip_matter_gap(model)
            results.append((full_gap, matter_gap))
            print(
                f"  {beta:<6g} "
                f"{hopping:<6g} "
                f"{model.dim:<8d} "
                f"{len(model.data):<12d} "
                f"{full_gap:<9.6g} "
                f"{plaquette.format_gap(matter_gap)} "
                f"{herm:.1e}"
            )
    finite_matter = [row[1] for row in results if np.isfinite(row[1])]
    assert min(row[0] for row in results) > 0.05
    assert finite_matter and min(finite_matter) > 1.0


def main():
    hd("Scope")
    print(
        "This is a 2D two-plaquette Z3 colour-orbit proxy with charged "
        "mirror-Fock/SMG matter, exact open-link Gauss projection, and sparse "
        "matrix-free Lanczos. It is still finite-volume and truncated."
    )
    scan()
    hd("Verdict")
    print(
        "The low-cutoff two-plaquette strip keeps a positive full gap and a "
        "matter-tagged excitation gap in the beta<=1 scan. The hopping audit "
        "shows this is not enough to claim mirror-gap stability: the next strip "
        "run must use a larger local cutoff and verify a visible t-response."
    )
    print("\nALL ASSERTS PASSED.")


if __name__ == "__main__":
    main()
