#!/usr/bin/env python3
r"""Wilson-axis no-bulk-transition argument for the SMG/TCH continuum route.

Scratch artifact; no canon update.

Question:
    Does the pure/fundamental Wilson SU(3) axis have no finite-beta bulk
    transition from beta_cert ~= 0.661156 to beta = infinity?

What can be derived internally:
    1. The registered SMG/TCH Hamiltonian induces no adjoint/irrelevant gauge
       deformation: lambda_i = 0 exactly.
    2. Therefore the path is the fundamental Wilson axis, not a mixed
       fundamental-adjoint path.
    3. beta_cert lies in the already-certified strong-coupling/endpoint side,
       and beta=infinity is the asymptotically-free continuum endpoint.

What cannot be derived from the finite TCH algebra alone:
    A global mathematical proof that pure SU(3) Wilson lattice gauge theory has
    no finite-beta nonanalyticity on the entire fundamental axis.  That is a
    standard lattice-gauge input supported by simulations and RG practice, not a
    theorem produced by the local SMG calculation.

This script encodes the strongest honest answer:

    conditional closure = exact TCH reduction to pure Wilson axis
                        + external Wilson-axis no-bulk-transition premise.

It also shows why the usual bulk-transition danger is removed here: it lives in
mixed-action directions such as beta_A != 0, while the registered mirror sector
sets beta_A=lambda_i=0 exactly.
"""

from __future__ import annotations

from dataclasses import dataclass


BETA_CERT = 0.661156
DELTA_CH_FLOOR = 3.960160
T_STRESS = 3.846019


@dataclass(frozen=True)
class Premise:
    label: str
    status: str
    content: str


def premises() -> list[Premise]:
    return [
        Premise(
            "P1 exact reduction",
            "derived in local TCH audit",
            "P_vac H P_ch=0 for electric, matter, magnetic, and hopping terms; "
            "hence beta_A=lambda_6=lambda_8=...=0.",
        ),
        Premise(
            "P2 endpoint health",
            "finite/certified",
            f"beta_cert={BETA_CERT:.6f}; charged gap floor in finite audit "
            f"Delta_ch>={DELTA_CH_FLOOR:.6f}; stress margin t_c={T_STRESS:.6f}.",
        ),
        Premise(
            "P3 Wilson-axis input",
            "external lattice-gauge premise",
            "Pure/fundamental Wilson SU(3) on the zero-temperature axis has no "
            "finite-beta bulk transition; observed/used as a crossover into the "
            "scaling region, unlike mixed fundamental-adjoint bulk surfaces.",
        ),
        Premise(
            "P4 quasi-adiabatic stability",
            "standard conditional theorem",
            "If the mirror block remains gapped, local perturbative continuation "
            "cannot change the massive spectator phase without gap closure.",
        ),
    ]


def decision_tree(wilson_axis_no_bulk: bool, new_pair_source: bool = False) -> str:
    if new_pair_source:
        return (
            "REOPENED: a new number-changing source adds lambda_pair <= eta^2/Delta; "
            "the pair source must be bounded against the nearest bulk surface."
        )
    if wilson_axis_no_bulk:
        return (
            "CLOSED-CONDITIONAL: SMG/TCH reduces exactly to the pure Wilson axis; "
            "with no Wilson-axis finite-beta bulk transition, the mirror block is a "
            "massive spectator to the continuum limit."
        )
    return (
        "BLOCKED: any finite-beta transition on the pure Wilson axis would be an "
        "ordinary gauge-sector obstruction, not mirror backreaction."
    )


def proof_skeleton() -> str:
    return r"""
Proof skeleton.

1. Let g=(beta_F,beta_A,lambda_6,lambda_8,...) denote local gauge-action
   coordinates.  By the exact block audit,

       P_vac O P_ch = 0

   for every registered local TCH/SMG operator O.  The Schrieffer-Wolff
   correction to the pure-gauge action therefore has no mirror excursion:

       delta g_mirror = 0.

   The RG path is gamma(beta)=(beta,0,0,0,...).

2. The known bulk-transition danger in SU(3) lattice gauge theory is a mixed
   action danger: adding adjoint/irrelevant couplings can create a first-order
   bulk surface and critical endpoint.  The path gamma(beta) has no such
   coordinates.  A transition would have to lie directly on the fundamental
   Wilson axis itself.

3. Strong-coupling analyticity covers a neighborhood of beta=0, and beta_cert
   is on that side of the certified local construction.  Weak-coupling RG gives
   the asymptotically-free continuum endpoint at beta=infinity.  The only
   missing global step is exclusion of an isolated finite-beta nonanalyticity
   between these regimes on the fundamental axis.

4. That exclusion is not generated by the finite SMG/TCH algebra.  It is the
   standard pure-Wilson SU(3) no-bulk-transition input.  With it, quasi-adiabatic
   continuation carries the massive mirror spectator block along the path.
"""


def main() -> int:
    print("[0] Wilson-axis no-bulk-transition argument")
    print(f"    beta_cert={BETA_CERT:.6f}")
    print(f"    finite charged-gap floor={DELTA_CH_FLOOR:.6f}")
    print(f"    finite stress margin t_c={T_STRESS:.6f}")
    assert 0.661 < BETA_CERT < 0.662
    assert DELTA_CH_FLOOR > 0.0
    assert T_STRESS > 1.0
    print()

    print("[1] premises")
    for p in premises():
        print(f"    {p.label}: {p.status}")
        print(f"      {p.content}")
    print()

    print("[2] proof skeleton")
    print(proof_skeleton().strip())
    print()

    print("[3] decision tree")
    print(f"    if Wilson-axis premise is accepted: {decision_tree(True)}")
    print(f"    if Wilson-axis premise fails:       {decision_tree(False)}")
    print(f"    if pair source is added:            {decision_tree(True, True)}")
    print()

    print("[VERDICT]")
    print("  The framework-specific derivation is complete: the SMG/TCH mirror block")
    print("  produces no induced beta_A or lambda_i, so the path is exactly the pure")
    print("  fundamental Wilson SU(3) axis plus a massive spectator. The remaining")
    print("  answer to the question is therefore not a TCH calculation but the standard")
    print("  lattice-gauge premise that the pure Wilson SU(3) axis has no finite-beta")
    print("  bulk transition. Under that premise, the continuum route closes conditionally;")
    print("  without it, the obstruction is pure gauge-sector physics.")
    print("exit 0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
