#!/usr/bin/env python3
r"""Finite-density Ward survival for gauge-fixed scalar causal-set QED.

Question:
  K21 left "finite-rho Ward" deferred.  Does the causal-set gauge-fixed scalar
  branch lose gauge invariance once the continuum kernel K(p)=p^2-m^2 is replaced
  by a finite-density / smeared causal-set kernel K_rho(p)?

Answer:
  No, provided the finite-density object is the ensemble/smeared translation-
  invariant kernel and it is gauged by link holonomies.  Ward is then an exact
  finite-difference identity, independent of the detailed kernel:

      k_mu Gamma^mu_rho(p+k,p) = K_rho(p+k) - K_rho(p).

  The same construction gives the two-photon/contact Ward identity

      k_mu Gamma^{mu nu}_rho(p;k,q)
        = Gamma^nu_rho(p+k;q) - Gamma^nu_rho(p;q).

  This is an algebraic result for the gauged kernel.  It does not say that a
  raw unsmeared sprinkling has low-variance numerics, and it does not solve the
  manifestly gauge-invariant loop F^2 action or Dirac spin.
"""

from __future__ import annotations

import numpy as np

G = np.diag([1.0, -1.0, -1.0])
M2 = 1.0


def mdot(a: np.ndarray, b: np.ndarray) -> float:
    return float(a @ G @ b)


def K_rho(p: np.ndarray) -> float:
    """Toy finite-density kernel: continuum pole plus Lorentz and nonlocal artifacts.

    The polynomial terms stand in for finite-rho/mesoscale corrections to the
    smeared causal-set d'Alembertian.  They are deliberately not just p^2; Ward
    should not care about the detailed form of K.
    """

    p2 = mdot(p, p)
    cubic = 0.013 * p[0] * p[1] * p[2]
    quartic = 0.06 * p2 * p2
    sixth = -0.004 * (p[0] ** 2 + 0.5 * p[1] ** 2 + 0.25 * p[2] ** 2) ** 3
    return p2 - M2 + quartic + cubic + sixth


def grad_hess_euclidean(p: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Euclidean gradient/Hessian of the finite-rho toy kernel."""

    p0, p1, p2 = p
    p_sq = mdot(p, p)
    grad_p_sq = np.array([2.0 * p0, -2.0 * p1, -2.0 * p2])
    hess_p_sq = np.diag([2.0, -2.0, -2.0])

    grad = grad_p_sq.copy()
    hess = hess_p_sq.copy()

    a = 0.06
    grad += 2.0 * a * p_sq * grad_p_sq
    hess += 2.0 * a * (np.outer(grad_p_sq, grad_p_sq) + p_sq * hess_p_sq)

    b = 0.013
    grad += b * np.array([p1 * p2, p0 * p2, p0 * p1])
    hess += b * np.array([[0.0, p2, p1], [p2, 0.0, p0], [p1, p0, 0.0]])

    c = -0.004
    r = p0**2 + 0.5 * p1**2 + 0.25 * p2**2
    grad_r = np.array([2.0 * p0, p1, 0.5 * p2])
    hess_r = np.diag([2.0, 1.0, 0.5])
    grad += 3.0 * c * r * r * grad_r
    hess += 3.0 * c * (2.0 * r * np.outer(grad_r, grad_r) + r * r * hess_r)

    return grad, hess


def grad_minkowski(p: np.ndarray) -> np.ndarray:
    """Metric-dual gradient Gamma satisfying mdot(v,Gamma)=d K(p+s v)/ds."""

    grad_e, _ = grad_hess_euclidean(p)
    return G @ grad_e


def hess_minkowski_matrix(p: np.ndarray) -> np.ndarray:
    """Matrix H with mdot(k,H[:,nu]) = d/ds grad_minkowski(p+s k)[nu]."""

    _, hess_e = grad_hess_euclidean(p)
    return G @ hess_e @ G


def gamma1(p: np.ndarray, k: np.ndarray, n: int = 1600) -> np.ndarray:
    """One-photon vertex from the gauged kernel: integral_0^1 ds grad K(p+s k)."""

    s = (np.arange(n) + 0.5) / n
    vals = np.array([grad_minkowski(p + si * k) for si in s])
    return vals.mean(axis=0)


def gamma2_contact(p: np.ndarray, k: np.ndarray, q: np.ndarray, n: int = 180) -> np.ndarray:
    """Two-photon/contact vertex generated by gauging gamma1 again.

    Constructed so that contracting the first index with k gives the finite
    difference of the one-photon vertex.  This is the nonlocal-kernel analog of
    the scalar-QED seagull/contact term.
    """

    s = (np.arange(n) + 0.5) / n
    mats = []
    for si in s:
        for ui in s:
            mats.append(hess_minkowski_matrix(p + si * k + ui * q))
    return np.mean(mats, axis=0)


def assert_close(label: str, lhs: np.ndarray | float, rhs: np.ndarray | float, tol: float) -> None:
    err = np.max(np.abs(lhs - rhs))
    print(f"    {label:<36} error = {err:.3e}")
    assert err < tol


print("[1] One-photon finite-rho Ward identity for an arbitrary smeared kernel K_rho")
p = np.array([1.35, 0.42, -0.31])
k = np.array([0.47, -0.18, 0.23])
g1 = gamma1(p, k)
lhs = mdot(k, g1)
rhs = K_rho(p + k) - K_rho(p)
print(f"    K_rho(p+k)-K_rho(p) = {rhs:+.12f}")
print(f"    k.Gamma_rho          = {lhs:+.12f}")
assert_close("one-photon Ward", lhs, rhs, 2e-8)
print("    -> Ward survives finite-rho artifacts because the vertex is the finite")
print("       difference of the gauged kernel, not because K_rho is exactly p^2-m^2.")

print("\n[2] Two-photon/contact Ward identity: finite-rho seagull generated automatically")
q = np.array([0.22, 0.33, -0.09])
contact = gamma2_contact(p, k, q)
lhs_vec = np.array([mdot(k, contact[:, nu]) for nu in range(3)])
rhs_vec = gamma1(p + k, q) - gamma1(p, q)
print(f"    k_mu Gamma^{{mu nu}} = {np.array2string(lhs_vec, precision=8)}")
print(f"    Delta Gamma^nu       = {np.array2string(rhs_vec, precision=8)}")
assert_close("two-photon/contact Ward", lhs_vec, rhs_vec, 2e-5)
print("    -> the contact/seagull term is not optional; it is the second gauging of")
print("       K_rho and cancels the finite-rho longitudinal variation.")

print("\n[3] Scope check")
print("    Applies to: ensemble/smeared translation-invariant causal-set kernels")
print("                (Johnston/BDG-style continuum-grade objects).")
print("    Does not apply to: a raw finite sprinkling before averaging/smearing, whose")
print("                operator entries are noisy and not exactly translation invariant.")
print("    Still open: manifest gauge-invariant loop F^2; Dirac spinor causal-set operator.")

print(
    r"""
[4] VERDICT
  Finite-rho Ward survival is CLOSED for the scalar, gauge-fixed causal-set QED
  branch at algebraic kernel grade:
    * replace K=p^2-m^2 by any smeared/ensemble finite-rho kernel K_rho(p);
    * gauge the kernel by link holonomies;
    * the one-photon and two-photon/contact Ward identities hold as exact finite
      differences of K_rho.

  This converts K21's "finite-rho Ward deferred" into a narrower statement:
  raw sprinkling variance remains a numerical/control issue, but gauge invariance
  of the smeared kernel is protected by the holonomy construction.  The genuine
  frontiers left are the manifestly gauge-invariant loop F^2 action and Dirac spin.
exit 0"""
)
print("ALL ASSERTIONS PASSED -- finite-rho scalar Ward identities survive by gauged-kernel algebra.")
