#!/usr/bin/env python3
r"""R4 REDUCED: complex Hilbert space FORCED by substrate-locality, not assumed.

R4 was the deepest open rung -- "why COMPLEX Hilbert space (over real / quaternionic)?". The prior
honest position (substrate_born_residual.py [4]) RELOCATED it to "why local tomography?", left as a
bare premise. This script reduces it one step further -- to the substrate's own locality -- mirroring
the R5 reduction (which pushed the [8,4,4] byte back onto the record axioms).

THE CHAIN
  (P) Local measurement structure: the substrate is a lattice of cells whose elementary measurements
      are single-cell syndrome reads; every measurement reduces to single-cell reads + classical
      post-processing (the operational content of a LOCAL substrate; R0 locality + R7 syndrome basis).
  =>  LOCAL TOMOGRAPHY: the composite effect space is then generated by products of local effects,
      E_AB = E_A (x) E_B, i.e. K_AB = K_A * K_B. (A measurement set with no irreducibly-collective
      primitive is locally tomographic by construction.)
  +   CONTINUOUS REVERSIBILITY: supplied by the unitary walk W (R3) -- a continuous reversible
      transitive action on pure states.
  =>  COMPLEX Hilbert space, uniquely (Hardy 2001; Chiribella-D'Ariano-Perinotti 2011): among general
      probabilistic theories, local tomography + continuous reversibility + the subspace axiom single
      out the field C. Real fails local tomography; quaternionic has no consistent tensor product;
      classical satisfies local tomography but has NO continuous reversible transitivity.

So COMPLEX is not assumed -- it is forced by {substrate locality -> local tomography} + {reversible
walk} via the reconstruction theorem. This is a REDUCTION (R5-grade), NOT an unconditional closure:
the residual is the locality premise (P) itself (natural for a lattice, but a premise) plus the
auxiliary reconstruction axioms (subspace, continuity, simplicity).

COMPUTABLE CORE -- the DISCRIMINATOR. Among the associative division algebras {R, C, H} (plus the
classical simplex), only C is locally tomographic AND continuously reversible. K_F(d) = real dimension
of the d x d Hermitian (state/observable) space over field F; local tomography <=> K_F(d_A d_B) =
K_F(d_A) K_F(d_B).
"""
from __future__ import annotations


def K_classical(d):  # simplex: d-outcome system, d unnormalised parameters
    return d


def K_real(d):       # real-symmetric d x d
    return d * (d + 1) // 2


def K_complex(d):    # complex-Hermitian d x d
    return d * d


def K_quaternionic(d):  # quaternionic-Hermitian d x d
    return d * (2 * d - 1)


def check(cond, msg):
    print(f"  [{'PASS' if cond else 'FAIL'}] {msg}")
    if not cond:
        raise AssertionError(msg)


def main():
    print("R4 REDUCED — complex Hilbert space from substrate-locality (local tomography), not assumed")
    print("=" * 100)

    FIELDS = [("classical", K_classical), ("real R", K_real),
              ("complex C", K_complex), ("quaternionic H", K_quaternionic)]

    # ---- [1] the local-tomography discriminator: K_AB =? K_A * K_B ----
    print("\n[1] LOCAL-TOMOGRAPHY DISCRIMINATOR  (K_AB = K_A*K_B ?)   composing two d=2 cells")
    print(f"  {'field':<16}{'K(2)':>6}{'K(2)*K(2)':>11}{'K(4)=K_AB':>11}{'gap':>6}  locally tomographic?")
    lt = {}
    for name, K in FIELDS:
        prod, comp = K(2) * K(2), K(4)
        gap = comp - prod
        lt[name] = (gap == 0)
        print(f"  {name:<16}{K(2):>6}{prod:>11}{comp:>11}{gap:>+6}  {lt[name]}")
    print("  gap>0 (real): hidden GLOBAL parameters local measurements cannot see; gap!=0 (H): the")
    print("  quaternionic tensor product is not even quaternionic (H(x)H = M_4(R); Araki) -> no composite.")

    # local tomography holds for complex AND classical; fails for real and quaternionic
    check(lt["complex C"], "complex is locally tomographic (K_AB = K_A*K_B)")
    check(lt["classical"], "classical (simplex) is also locally tomographic")
    check(not lt["real R"], "real FAILS local tomography (over-counts)")
    check(not lt["quaternionic H"], "quaternionic FAILS (count mismatch; no consistent tensor product)")

    # robustness across dimensions: complex stays LT, real keeps failing
    for dA, dB in [(2, 2), (2, 3), (3, 3), (2, 4)]:
        check(K_complex(dA * dB) == K_complex(dA) * K_complex(dB),
              f"complex LT holds at (d_A,d_B)=({dA},{dB})")
        check(K_real(dA * dB) != K_real(dA) * K_real(dB),
              f"real LT fails at (d_A,d_B)=({dA},{dB})")

    # ---- [2] the famous hidden parameter, concretely (2 qubits vs 2 rebits) ----
    print("\n[2] THE HIDDEN GLOBAL PARAMETER, concretely")
    qubit = K_complex(4) - K_complex(2) * K_complex(2)   # 16 - 16 = 0
    rebit = K_real(4) - K_real(2) * K_real(2)            # 10 -  9 = 1
    print(f"  2 qubits (complex): full state dim {K_complex(4)} vs locally-accessible {K_complex(2)*K_complex(2)}  -> gap {qubit}")
    print(f"  2 rebits (real)   : full state dim {K_real(4)} vs locally-accessible {K_real(2)*K_real(2)}  -> gap {rebit}")
    check(qubit == 0 and rebit == 1,
          "complex: local measurements are COMPLETE; real has exactly 1 locally-invisible global state")
    print("  -> in a substrate where every measurement is local, the real theory's hidden global state")
    print("     is undetectable in principle; the theory with NO locally-invisible states is complex.")

    # ---- [3] local tomography alone leaves {classical, complex}; reversibility picks complex ----
    print("\n[3] WHY NOT CLASSICAL: local tomography is necessary, not sufficient")
    print("  classical (simplex) is locally tomographic too, so local tomography selects {classical, C}.")
    print("  The substrate's unitary walk W (R3) is a CONTINUOUS reversible transitive action on pure")
    print("  states; the classical simplex has only discrete symmetries (no continuous transitivity).")
    print("  So reversibility excludes classical -> the unique survivor is COMPLEX C.")
    check(lt["classical"] and lt["complex C"],
          "local tomography alone admits both classical and complex; reversibility (the walk) breaks the tie")

    print(f"""
{"=" * 100}
VERDICT (exit 0):  R4 is REDUCED from "complex assumed / relocated to bare local tomography" to
"complex FORCED by substrate-locality + reversibility", at R5 grade -- a reduction, not a closure.

  THE REDUCTION.  (P) the substrate's measurements are locally generated (single-cell syndrome reads;
  no irreducibly-collective primitive -- the operational meaning of a local lattice, R0/R7) => LOCAL
  TOMOGRAPHY (E_AB = E_A (x) E_B, computed above: only C and the classical simplex qualify; real and
  quaternionic are excluded by the dimension count / tensor non-existence).  The unitary walk W (R3)
  supplies CONTINUOUS REVERSIBILITY, which excludes the classical simplex.  By the reconstruction
  theorems (Hardy 2001; Chiribella-D'Ariano-Perinotti 2011), local tomography + continuous
  reversibility + the subspace axiom single out the field C.  Hence COMPLEX Hilbert space is forced,
  not posited.

  WHAT THIS CLOSES.  The "why complex over real/quaternionic" half is now a computed discriminator:
  local tomography is the exact sieve (real over-counts by the rebit parameter; quaternionic has no
  tensor product), and the framework SUPPLIES local tomography from its locality rather than assuming
  it.  This de-relocates "why complex" back to R0 (records/measurements are local) -- the axiom floor.

  HONEST RESIDUAL (why this is REDUCED, not Locked).  (i) the locality premise (P) -- "every
  measurement is single-cell-generated" -- is natural for a lattice but is itself the load-bearing
  premise (a collective measurement primitive would reopen real QM); (ii) the auxiliary reconstruction
  axioms (subspace, continuity, simplicity) are supplied by the QEC code + walk but each mapping needs
  to be made rigorous, not just asserted; (iii) the reconstruction theorem itself is imported, not
  re-proved here.  So R4 stands exactly where R5 stands: the deep hypothesis is reduced to a small,
  named, natural premise + a cited theorem, with the computable discriminator verified.
{"=" * 100}""")
    print("exit 0 -- R4 reduced: locality -> local tomography (only C passes; real/H excluded, computed) "
          "+ reversible walk excludes classical -> complex forced (Hardy/CDP); residual = the locality premise + auxiliary axioms.")


if __name__ == "__main__":
    main()
