#!/usr/bin/env python3
r"""Few-cell non-abelian Wilson-loop cluster with a declared record-action measure.

Purpose
-------
This is the first "real physics" extension of the record-grammar ladder beyond
one plaquette.  It asks whether a small non-abelian loop ledger can be both:

  * a detector interface: rectangular Wilson loops W(C) are gauge-readable
    records; and
  * a tractable representation: the many rectangular loops are generated by a
    small area-law ledger rather than stored as a flat list.

Declared measure
----------------
Use a two-dimensional SU(2) pure-gauge record-action model.  In axial gauge the
independent records are plaquette holonomies U_p with measure

    dP(U_p) proportional to dHaar(U_p) exp[ beta Re Tr(U_p) / 2 ].

A rectangular loop of area A is the ordered product of the A plaquette records
inside it,

    W(C) = (1/2) Re Tr prod_{p inside C} U_p.

For this 2D axial-gauge measure the fundamental Wilson-loop expectation is
exactly an area law:

    <W(C)> = a(beta)^A,

where

    a(beta) = <(1/2) Re Tr U_p>

under the one-plaquette measure.  The script computes a(beta) by quadrature,
samples the measure by Monte Carlo as a check, fits

    -log <W(C)> = sigma A + mu P + c,

and reports the ledger-size scaling.

Boundary
--------
This is not a four-dimensional Yang-Mills derivation and not yet the full TCH
cell dynamics.  It is a controlled two-dimensional non-abelian record-action
certificate: area law appears from the declared local loop measure, and the
ledger compresses rectangular Wilson-loop records to one string-tension record
plus local plaquette records.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np


I2 = np.eye(2, dtype=complex)
X = np.array([[0, 1], [1, 0]], dtype=complex)
Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z = np.array([[1, 0], [0, -1]], dtype=complex)
PAULIS = np.array([X, Y, Z])


@dataclass(frozen=True)
class LoopRow:
    width: int
    height: int
    area: int
    perimeter: int
    exact: float
    mc_mean: float | None = None
    mc_stderr: float | None = None


def assert_close(name: str, value: float, target: float, tol: float = 1e-10) -> None:
    err = abs(value - target)
    print(f"  {name:<74s} value={value:.12g} target={target:.12g} err={err:.3e}")
    if err > tol:
        raise AssertionError(name)


def assert_less(name: str, value: float, bound: float) -> None:
    print(f"  {name:<74s} value={value:.12g} bound={bound:.12g}")
    if not value < bound:
        raise AssertionError(name)


def assert_greater(name: str, value: float, bound: float) -> None:
    print(f"  {name:<74s} value={value:.12g} bound={bound:.12g}")
    if not value > bound:
        raise AssertionError(name)


def su2_from_axis(axis: np.ndarray, cos_theta: float) -> np.ndarray:
    """Return cos(theta) I + i sin(theta) axis.sigma."""

    axis = axis / np.linalg.norm(axis)
    sin_theta = math.sqrt(max(0.0, 1.0 - cos_theta * cos_theta))
    generator = axis[0] * X + axis[1] * Y + axis[2] * Z
    return cos_theta * I2 + 1j * sin_theta * generator


def random_sphere_axis(rng: np.random.Generator) -> np.ndarray:
    v = rng.normal(size=3)
    return v / np.linalg.norm(v)


def sample_su2_wilson(beta: float, rng: np.random.Generator) -> np.ndarray:
    """Sample SU(2) with density proportional to Haar(U) exp(beta ReTr(U)/2).

    Write U = x I + i sqrt(1-x^2) n.sigma.  Haar gives density
    sqrt(1-x^2) dx dOmega.  The action weight is exp(beta x).
    Rejection from uniform x in [-1,1] uses the envelope
    sqrt(1-x^2) exp(beta(x-1)) <= 1.
    """

    while True:
        x = rng.uniform(-1.0, 1.0)
        accept = math.sqrt(max(0.0, 1.0 - x * x)) * math.exp(beta * (x - 1.0))
        if rng.random() <= accept:
            return su2_from_axis(random_sphere_axis(rng), x)


def one_plaquette_mean(beta: float, n_quad: int = 512) -> float:
    """Compute a(beta)=<ReTr U/2> by Gauss-Legendre quadrature."""

    x, w = np.polynomial.legendre.leggauss(n_quad)
    density = np.sqrt(np.maximum(0.0, 1.0 - x * x)) * np.exp(beta * x)
    z0 = float(np.sum(w * density))
    z1 = float(np.sum(w * x * density))
    return z1 / z0


def sample_plaquette_lattice(size: int, beta: float, rng: np.random.Generator) -> np.ndarray:
    """Return an open size x size array of independent axial-gauge plaquette records."""

    out = np.empty((size, size, 2, 2), dtype=complex)
    for y in range(size):
        for x in range(size):
            out[y, x] = sample_su2_wilson(beta, rng)
    return out


def rectangle_loop(plaquettes: np.ndarray, x0: int, y0: int, width: int, height: int) -> float:
    """Normalized Wilson loop from the ordered product of interior plaquette records."""

    prod = I2.copy()
    for y in range(y0, y0 + height):
        for x in range(x0, x0 + width):
            prod = prod @ plaquettes[y, x]
    return float(np.real(np.trace(prod)) / 2.0)


def all_rectangle_values(plaquettes: np.ndarray, width: int, height: int) -> np.ndarray:
    size = plaquettes.shape[0]
    vals = []
    for y0 in range(size - height + 1):
        for x0 in range(size - width + 1):
            vals.append(rectangle_loop(plaquettes, x0, y0, width, height))
    return np.array(vals, dtype=float)


def exact_loop_rows(size: int, beta: float) -> list[LoopRow]:
    a = one_plaquette_mean(beta)
    rows: list[LoopRow] = []
    for height in range(1, size + 1):
        for width in range(1, size + 1):
            area = width * height
            perimeter = 2 * (width + height)
            rows.append(LoopRow(width, height, area, perimeter, a**area))
    return rows


def fit_area_perimeter(rows: list[LoopRow], use_mc: bool = False) -> tuple[float, float, float, float]:
    """Least-squares fit y = sigma A + mu P + c.  Return sigma, mu, c, max residual."""

    xs = []
    ys = []
    for row in rows:
        val = row.mc_mean if use_mc else row.exact
        if val is None or val <= 0.0:
            continue
        xs.append([row.area, row.perimeter, 1.0])
        ys.append(-math.log(val))
    Xmat = np.array(xs, dtype=float)
    yvec = np.array(ys, dtype=float)
    coeff, *_ = np.linalg.lstsq(Xmat, yvec, rcond=None)
    resid = yvec - Xmat @ coeff
    return float(coeff[0]), float(coeff[1]), float(coeff[2]), float(np.max(np.abs(resid)))


def monte_carlo_rows(
    size: int,
    beta: float,
    rng: np.random.Generator,
    n_cfg: int = 2500,
    max_area: int = 4,
) -> list[LoopRow]:
    """Measure small rectangular loops.  Large-area loops are exact-only in this script."""

    exact = {(r.width, r.height): r for r in exact_loop_rows(size, beta)}
    values: dict[tuple[int, int], list[float]] = {
        (w, h): []
        for h in range(1, size + 1)
        for w in range(1, size + 1)
        if w * h <= max_area
    }
    for _ in range(n_cfg):
        plaq = sample_plaquette_lattice(size, beta, rng)
        for (w, h), bucket in values.items():
            # Average over translations inside this configuration.  This lowers
            # variance and matches the detector reading of a loop shape rather
            # than one fixed placement.
            bucket.append(float(np.mean(all_rectangle_values(plaq, w, h))))

    out: list[LoopRow] = []
    for (w, h), bucket in sorted(values.items(), key=lambda x: (x[0][0] * x[0][1], x[0][1], x[0][0])):
        arr = np.array(bucket, dtype=float)
        base = exact[(w, h)]
        out.append(
            LoopRow(
                width=w,
                height=h,
                area=base.area,
                perimeter=base.perimeter,
                exact=base.exact,
                mc_mean=float(np.mean(arr)),
                mc_stderr=float(np.std(arr, ddof=1) / math.sqrt(len(arr))),
            )
        )
    return out


def ledger_report(size: int, residual_promotions: int) -> dict[str, int]:
    """Simple ledger count for an open size x size plaquette cluster."""

    byte_vertices = (size + 1) * (size + 1)
    stabilizer_generators = 8 * byte_vertices  # four X(C) plus four Z(C) generators per byte endpoint
    link_records_before_gauge = 2 * size * (size + 1)
    local_plaquette_records = size * size
    flat_rectangle_records = (size * (size + 1) // 2) ** 2
    promoted_collective_records = 1 + residual_promotions  # one string-tension/area-law record
    generator_ledger_size = stabilizer_generators + local_plaquette_records + promoted_collective_records
    return {
        "byte_vertices": byte_vertices,
        "stabilizer_generators": stabilizer_generators,
        "link_records_before_gauge": link_records_before_gauge,
        "local_plaquette_records": local_plaquette_records,
        "flat_rectangle_records": flat_rectangle_records,
        "promoted_collective_records": promoted_collective_records,
        "generator_ledger_size": generator_ledger_size,
        "bond_dimension_proxy": 1,
    }


def main() -> None:
    print("Few-cell non-abelian Wilson-loop cluster: SU(2) record-action area-law certificate")
    print("=" * 104)

    beta = 2.0
    rng = np.random.default_rng(20260629)
    a = one_plaquette_mean(beta)
    sigma_exact = -math.log(a)
    print("\n[1] Declared record-action measure")
    print("  dP(U_p) proportional to dHaar(U_p) exp[ beta ReTr(U_p)/2 ]")
    print(f"  beta = {beta:.3f}")
    print(f"  a(beta)=<ReTr(U_p)/2> = {a:.12f}")
    print(f"  exact 2D area-law string tension sigma = -log a = {sigma_exact:.12f}")
    assert_greater("one-plaquette trace coefficient", a, 0.0)
    assert_less("one-plaquette trace coefficient", a, 1.0)

    print("\n[2] Exact Wilson-loop area/perimeter fit on a few-cell cluster")
    size = 6
    exact_rows = exact_loop_rows(size=size, beta=beta)
    sigma, mu, c0, max_resid = fit_area_perimeter(exact_rows)
    print(f"  cluster: {size} x {size} plaquette records")
    print(f"  fit -log<W> = sigma A + mu P + c over {len(exact_rows)} rectangle classes")
    print(f"  sigma={sigma:.12f}, mu={mu:.3e}, c={c0:.3e}, max residual={max_resid:.3e}")
    assert_close("fit sigma equals exact area tension", sigma, sigma_exact, tol=1e-11)
    assert_less("perimeter coefficient vanishes in 2D axial-gauge model", abs(mu), 1e-11)
    assert_less("fit constant vanishes", abs(c0), 1e-11)
    assert_less("area-law residual", max_resid, 1e-10)

    print("\n[3] Monte Carlo check of the loop detector records")
    mc_rows = monte_carlo_rows(size=size, beta=beta, rng=rng, n_cfg=2500, max_area=4)
    print("  w x h   A   P       exact <W>      measured <W>       stderr      z")
    max_z = 0.0
    for row in mc_rows:
        assert row.mc_mean is not None and row.mc_stderr is not None
        z = abs(row.mc_mean - row.exact) / max(row.mc_stderr, 1e-300)
        max_z = max(max_z, z)
        print(
            f"  {row.width:1d} x {row.height:<1d}  {row.area:2d}  {row.perimeter:2d}"
            f"   {row.exact: .8e}   {row.mc_mean: .8e}   {row.mc_stderr: .2e}   {z:5.2f}"
        )
    assert_less("Monte Carlo max z-score against exact area law", max_z, 4.0)

    mc_sigma, mc_mu, mc_c, mc_resid = fit_area_perimeter(mc_rows, use_mc=True)
    print(
        f"  MC fit over area<=4: sigma={mc_sigma:.6f}, mu={mc_mu:.3e}, "
        f"c={mc_c:.3e}, max residual={mc_resid:.3e}"
    )
    print("  (The coefficient gate is the exact area-law fit above; this MC fit is a noisy sanity check.)")
    assert_less("MC sigma within 15 percent", abs(mc_sigma / sigma_exact - 1.0), 0.15)

    print("\n[4] Ledger-size and promotion/bond-dimension scaling")
    print(
        "  L  byte  stab_gen  link_rec  plaq_rec  flat_rect  promoted  bondD  generator_ledger"
    )
    for L in range(2, 9):
        rows = exact_loop_rows(size=L, beta=beta)
        _, _, _, resid = fit_area_perimeter(rows)
        residual_promotions = sum(
            1 for r in rows if abs(-math.log(r.exact) - sigma_exact * r.area) > 1e-10
        )
        led = ledger_report(L, residual_promotions=residual_promotions)
        print(
            f"  {L:<2d} {led['byte_vertices']:5d} {led['stabilizer_generators']:9d}"
            f" {led['link_records_before_gauge']:9d} {led['local_plaquette_records']:9d}"
            f" {led['flat_rectangle_records']:10d} {led['promoted_collective_records']:9d}"
            f" {led['bond_dimension_proxy']:6d} {led['generator_ledger_size']:17d}"
        )
        assert_less(f"L={L} exact area-law fit residual", resid, 1e-10)
        assert led["promoted_collective_records"] == 1
        assert led["bond_dimension_proxy"] == 1
        # The generator ledger is O(L^2); the flat rectangular-loop list is O(L^4).
        assert led["generator_ledger_size"] < 16 * (L + 1) * (L + 1)

    print("\n[5] Detector-interface / tractability verdict")
    print(
        """
The detector interface is the normalized Wilson-loop trace.  The tractable
representation is the same object in generator form: local plaquette records
plus one promoted collective area-law/string-tension record.  In this 2D
record-action model, all rectangular Wilson-loop expectations are generated by
one coefficient a(beta), so the perimeter term and residual promotions vanish.

This is the first rung, not the full confinement theorem:
  PASS: non-abelian loop records on a few-cell cluster;
  PASS: declared record-action measure;
  PASS: area-law fit and sigma extraction in native units;
  PASS: flat rectangular-loop list replaced by an O(L^2) generator ledger;
  OPEN: 3D/4D TCH dynamics, SU(3), mirror matter, and continuum Yang-Mills.
"""
    )
    print("exit 0 -- non-abelian Wilson-cluster area-law ledger certificate passed.")


if __name__ == "__main__":
    main()
