#!/usr/bin/env python3
r"""ITEM 87 -- PMNS angle promotion gate after the K_or recovery-holonomy work.

Question
--------
The active-neutrino masses are pinned by the delta_nu=1/3 Koide/circulant
branch, but theta_13 is only bracketed: a bare circulant gives trimaximal
theta_13=35.26 deg, while matching charged and neutral circulants gives
theta_13=0.  Does the newer K_or/sign-pointer recovery-holonomy algebra move
the PMNS angles, or does it only address CP orientation?

Answer
------
It does not move the angles.  The scalar-plus-sign algebra generated by
I, A_K3, and K_or is still the C3/circulant algebra.  It is diagonalized by
the DFT, so it keeps the same trimaximal eigenvectors.  Majorana
symmetrisation also removes the directed support, leaving A_K3 as support and
using K_or only as an orientation/phase label.

The observed/bimaximal PMNS matrices require a large residual outside the
C3/circulant algebra: a standard-representation texture, not merely the
sign-representation pointer.  A universal 2/9 charged-lepton rotation gives
theta_13 near 9 deg, but not the QLC theta_12=45-2/9 value.  Therefore the
best current progress is a sharper target:

    derive a standard-representation charged-lepton/neutrino texture.

K_or remains relevant for CP sign/orientation, not for the three PMNS angles.
"""

from __future__ import annotations

from itertools import permutations
import math

import numpy as np


TOL = 1.0e-10
MASSES = np.array([0.79e-3, 8.72e-3, 50.2e-3])
OBS = (33.44, 49.2, 8.57)  # representative NuFIT-5.x normal-ordering values used in repo audits
DELTA = 2.0 / 9.0


def check(condition: bool, message: str) -> None:
    print(f"  [{'PASS' if condition else 'FAIL'}] {message}")
    if not condition:
        raise AssertionError(message)


def angles_deg(u: np.ndarray) -> tuple[float, float, float]:
    s13sq = abs(u[0, 2]) ** 2
    s12sq = abs(u[0, 1]) ** 2 / max(1.0 - s13sq, 1.0e-15)
    s23sq = abs(u[1, 2]) ** 2 / max(1.0 - s13sq, 1.0e-15)
    return tuple(
        float(np.degrees(np.arcsin(np.sqrt(np.clip(x, 0.0, 1.0)))))
        for x in (s12sq, s23sq, s13sq)
    )


def dft3() -> np.ndarray:
    w = np.exp(2j * np.pi / 3.0)
    return np.array([[w ** (j * k) for k in range(3)] for j in range(3)], dtype=complex) / np.sqrt(3.0)


def cycle() -> np.ndarray:
    return np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]], dtype=complex)


def a_k3() -> np.ndarray:
    return np.ones((3, 3), dtype=complex) - np.eye(3, dtype=complex)


def k_or() -> np.ndarray:
    p = cycle()
    return p - p.T


def r12(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, s, 0], [-s, c, 0], [0, 0, 1]], dtype=complex)


def r23(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[1, 0, 0], [0, c, s], [0, -s, c]], dtype=complex)


def r13(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, 0, s], [0, 1, 0], [-s, 0, c]], dtype=complex)


def pmns_pdg(t12: float, t23: float, t13: float, dcp: float = 0.0) -> np.ndarray:
    t12, t23, t13 = np.radians([t12, t23, t13])
    s12, c12 = np.sin(t12), np.cos(t12)
    s23, c23 = np.sin(t23), np.cos(t23)
    s13, c13 = np.sin(t13), np.cos(t13)
    phase = np.exp(-1j * dcp)
    u23 = np.array([[1, 0, 0], [0, c23, s23], [0, -s23, c23]], dtype=complex)
    u13 = np.array(
        [[c13, 0, s13 * phase], [0, 1, 0], [-s13 * np.conj(phase), 0, c13]],
        dtype=complex,
    )
    u12 = np.array([[c12, s12, 0], [-s12, c12, 0], [0, 0, 1]], dtype=complex)
    return u23 @ u13 @ u12


def majorana_mass_from_angles(angles: tuple[float, float, float]) -> np.ndarray:
    u = pmns_pdg(*angles)
    return u.conj() @ np.diag(MASSES) @ u.conj().T


def project_c3(mat: np.ndarray) -> np.ndarray:
    p = cycle()
    return sum(np.linalg.matrix_power(p, k).conj().T @ mat @ np.linalg.matrix_power(p, k) for k in range(3)) / 3.0


def permutation_matrices() -> list[tuple[np.ndarray, int]]:
    out: list[tuple[np.ndarray, int]] = []
    eye = np.eye(3, dtype=complex)
    for perm in permutations(range(3)):
        inversions = sum(1 for i in range(3) for j in range(i + 1, 3) if perm[i] > perm[j])
        out.append((eye[list(perm)], -1 if inversions % 2 else 1))
    return out


def sign_average(mat: np.ndarray) -> np.ndarray:
    out = np.zeros_like(mat, dtype=complex)
    for p, parity in permutation_matrices():
        out += parity * (p.T @ mat @ p)
    return out / 6.0


def gate_kor_cannot_move_angles() -> None:
    print("\n[1] K_or/sign-pointer algebra is still C3-circulant")
    eye = np.eye(3, dtype=complex)
    a = a_k3()
    k = k_or()
    f = dft3()
    h = 0.7 * eye + 0.31 * a + 0.19j * k  # Hermitian C3 algebra element
    diag = f.conj().T @ h @ f
    offdiag = np.linalg.norm(diag - np.diag(np.diag(diag)))
    t12, t23, t13 = angles_deg(f)
    print(f"  ||F^dag H F - diagonal|| = {offdiag:.3e}")
    print(f"  DFT eigenvector angles = ({t12:.2f}, {t23:.2f}, {t13:.2f}) deg")
    check(offdiag < TOL, "I, A_K3, and i K_or share the DFT eigenbasis")
    check(abs(t13 - 35.26438968) < 1.0e-6, "the shared eigenbasis is trimaximal, not theta_13 ~= 8.6 deg")
    check(abs(angles_deg(f.conj().T @ f)[2]) < TOL, "if charged leptons share the same circulant basis, theta_13 collapses to 0")

    p_plus = cycle()
    sym = p_plus + p_plus.T
    check(np.linalg.norm(sym - a) < TOL, "Majorana symmetrisation of the directed latch gives A_K3")
    check(np.linalg.norm(sign_average(a)) < TOL, "the sign pointer rejects the scalar support A_K3")
    check(np.linalg.norm(sign_average(k) - k) < TOL, "the sign pointer reads K_or as orientation")
    print("  Conclusion: K_or is a CP-orientation carrier.  It is not a PMNS-angle texture.")


def gate_target_requires_standard_rep() -> None:
    print("\n[2] Observed and QLC PMNS matrices require non-circulant standard texture")
    qlc = (45.0 - math.degrees(DELTA), 45.0, math.degrees(DELTA) / math.sqrt(2.0))
    for name, angles in (("observed-representative", OBS), ("QLC 2/9 bimaximal", qlc)):
        mat = majorana_mass_from_angles(angles)
        c3 = project_c3(mat)
        resid = mat - c3
        frac = np.linalg.norm(resid) / np.linalg.norm(mat)
        print(f"  {name:24s}: angles={tuple(round(x, 3) for x in angles)}, C3 residual={frac:.3f}")
        check(frac > 0.45, f"{name} needs a large component outside the C3/circulant algebra")
    print("  This residual is the missing standard-representation texture; scalar plus sign data are insufficient.")


def gate_universal_2_9_correction() -> None:
    print("\n[3] Universal 2/9 charged-lepton correction helps theta_13 but does not derive QLC")
    ubi = r23(np.pi / 4.0) @ r12(np.pi / 4.0)
    charged_12 = r12(DELTA).T @ ubi
    corrected = angles_deg(charged_12)
    qlc = (45.0 - math.degrees(DELTA), 45.0, math.degrees(DELTA) / math.sqrt(2.0))
    constructed = angles_deg(r23(np.pi / 4.0) @ r13(DELTA / math.sqrt(2.0)) @ r12(np.pi / 4.0 - DELTA))
    print(f"  U_e(12,2/9)^dag U_bimax angles = {tuple(round(x, 3) for x in corrected)}")
    print(f"  QLC constructed angles          = {tuple(round(x, 3) for x in constructed)}")
    print(f"  QLC target formula              = {tuple(round(x, 3) for x in qlc)}")
    check(abs(corrected[2] - qlc[2]) < 0.1, "a 2/9 left 1-2 correction naturally gives theta_13 ~= delta/sqrt2")
    check(abs(corrected[0] - qlc[0]) > 3.0, "the same simple correction misses theta_12=45-delta")
    check(np.linalg.norm(np.array(constructed) - np.array(qlc)) < 1.0e-9, "the QLC numbers are obtainable only by constructing that texture")
    print("  Therefore the attractive 2/9 PMNS formula is matched, but the texture is still not derived.")


def main() -> int:
    print("ITEM 87 -- PMNS ANGLE PROMOTION GATE")
    print("=" * 88)
    gate_kor_cannot_move_angles()
    gate_target_requires_standard_rep()
    gate_universal_2_9_correction()
    print(
        """
VERDICT
  Progress is mostly negative but useful:
    * the recent K_or/sign-pointer work cannot fix theta_13.  It lives inside
      the C3/circulant algebra and leaves the DFT eigenvectors untouched;
    * the measured/QLC PMNS textures need a large standard-representation
      residual, not just scalar A_K3 plus sign K_or;
    * the universal 2/9 twist naturally gives theta_13 ~= delta/sqrt(2) in a
      charged-lepton correction, but it does not also give theta_12=45-delta.

  The remaining theorem target is therefore precise:
      derive a standard-representation charged-lepton/neutrino texture whose
      strength is tied to the universal 2/9 service/charge primitive.

exit 0 -- PMNS angles remain matched/achievable but not predicted; K_or is CP-orientation, not angle texture.
"""
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
